Boleto Bancário
<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   payment
 * @package    Alex
 * @copyright  Copyright (c) 2016 Alex (www.kaisan.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Alex <>
 */




$configmodulo = Mage::getSingleton('bradescoce2/payment');
$order        = $this->getInfo()->getOrder();

$customer_id = $order->getCustomerId();
$customerData = Mage::getModel('customer/customer')->load($customer_id);



if($this->getInfo() && $order){

    echo "<a href='" . $this->getUrl('bradescoce2/index/registrarBoleto') . "?id_pedido=" . $order->getId() . "& id_cliente=" . $cliente->getId() . "'><img src=\"<?php echo $this->getSkinUrl('images/Oitoo_Bradescocomercioeletronico2/icon-pag-boleto.png'); ?>\"></a>";

}