Boleto Bancário
<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   payment
 * @package    Alex
 * @copyright  Copyright (c) 2016 Alex (www.kaisan.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Alex <>
 */
$configmodulo = Mage::getSingleton('bradescoce2/payment');
$ambienteproducao = $configmodulo->getConfigData('ambiente', Mage::app()->getStore()->getId());
$merchantid = $configmodulo->getConfigData('merchantid', Mage::app()->getStore()->getId());


if($this->getInfo()){

    if($this->getInfo()->getOrder()){
        $orderId = $this->getInfo()->getOrder()->getIncrementId();

        ?>

        <br><br>

        Clique na imagem abaixo para imprimir a segunda via do boleto.<br>
        <a href="<?php  if($ambienteproducao) { echo "https://mup.comercioeletronico.com.br/sepsBoleto/" . $merchantid . "/prepara_pagto.asp?merchantid=" . $merchantid . "&orderid=" . $orderId; } else { echo "http://mupteste.comercioeletronico.com.br/sepsBoleto/" . $merchantid . "/prepara_pagto.asp?merchantid=" . $merchantid . "&orderid=" . $orderId;  } ?>"><img src="<?php echo $this->getSkinUrl('images/Oitoo_Bradescocomercioeletronico2/icon-pag-boleto.png'); ?>"></a>

    <?php }} ?>